---
# -- Site Configuration --
theme: blowfish
baseURL: https://mirceanton.netlify.app/
defaultContentLanguage: en

timeout: 120s

enableRobotsTXT: true
paginate: 20
summaryLength: 30

buildDrafts: false
buildFuture: false

googleAnalytics: G-RE0K14YZ9P

taxonomies:
  tag: tags
  category: categories
  author: authors
  series: series

sitemap:
  changefreq: daily
  filename: sitemap.xml
  priority: 0.5

outputs:
  home: 
    - HTML
    - RSS
    - JSON
