# -- Language Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://nunocoracao.github.io/blowfish/docs/configuration/#language-and-i18n
---
languageCode: en
languageName: English
displayName: EN
isoCode: en
weight: 1
rtl: false

# The title of the website. This will be displayed in the site header and footer
title: Mircea Anton

# The website description. This will be used in the site metadata.
description: My awesome website

logo: images/logo-icon.png # Icon in navbar

# A Markdown string containing the copyright message to be displayed in the site footer
copyright: Copyright © Anton Mircea-Pavel, 2023

# How dates are formatted in this language. Refer to the Hugo docs for acceptable formats.
# https://gohugo.io/functions/format/#gos-layout-string
dateFormat: 2 January 2006

# This will be displayed in article footers, and on the homepage when the profile layout is used.
author:
  name: Mircea-Pavel Anton
  image: images/logo.png
  headline: DevOps engineer by day, drummer & gym rat by night
  bio: I meme, therefore I am.
  links:
    - email: mailto:contact@mirceanton.com
    - github: https://github.com/mirceanton
    # - gitlab: https://gitlab.com/mirceanton
    - instagram: https://instagram.com/_mirceanton
    - linkedin: https://linkedin.com/in/mirceanton
    # - youtube: https://youtube.com/in/mirceanton
    # - patreon: https://patreon.com/mirceanton
    # - reddit: https://reddit.com/u/mikeanth
    # - steam: https://steamcommunity.com/profiles/mikeanth
