---
include:
  - local: .gitlab/templates/terraform.gitlab-ci.yml

stages:
  - terraform-validate
  - terraform-plan
  - terraform-apply
  - build
  - deploy

tf-validate:
  extends: .terraform-base
  stage: terraform-validate
  script: terraform validate

tf-plan:
  extends: .terraform-base
  stage: terraform-plan
  script: terraform plan
  needs:
    - tf-validate

tf-apply:
  extends: .terraform-base
  stage: terraform-apply
  script: terraform apply -auto-approve
  needs:
    - tf-plan

hugo:
  image: registry.gitlab.com/pages/hugo/hugo_extended:latest
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    HUGO_ENV: production
  script:
    - hugo --gc --minify -s website/ -d ../public/
  artifacts:
    paths:
      - ./public/

cloudflare-deploy:
  image: node:lts-slim
  stage: deploy
  script:
    - npm install
    - npx wrangler pages publish ./public/
        --project-name mirceanton
        --branch $CI_COMMIT_BRANCH
        --commit-hash $CI_COMMIT_SHA
        --commit-message "$CI_COMMIT_MESSAGE"
  needs:
    - hugo
