# =================================================================================================
# BUILD SETTINGS
# =================================================================================================
[build]
  command = "hugo --gc --minify"
  base = "website/"
  publish = "public"

[build.environment]
  TZ = "Europe/Bucharest"
  HUGO_VERSION = "0.107.0"
  
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# =================================================================================================
# DEPLOY PREVIEWS
# =================================================================================================
[context.deploy-preview]
  command = "hugo --gc --buildDrafts --buildFuture"
  base = "website/"
  publish = "public"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.107.0"

# =================================================================================================
# FUNCTIONS
# =================================================================================================
[functions]
  directory = "functions/"

# =================================================================================================
# BUILD PLUGINS
# =================================================================================================
[[plugins]]
  package = "@netlify/plugin-lighthouse"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"