# =================================================================================================
# BUILD SETTINGS
# =================================================================================================
[build]
  publish = "public"
  command = "hugo --gc --minify -s website/ -d ../public/"

# =================================================================================================
# CONTEXT SETTINGS
# =================================================================================================
[context.production.environment]
  HUGO_VERSION = "0.110.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[context.split1]
  command = "hugo --gc --minify -s website/ -d ../public/ --enableGitInfo"

[context.split1.environment]
  HUGO_VERSION = "0.110.0"
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify -s website/ -d ../public/ --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.110.0"

[context.branch-deploy]
  command = "hugo --gc --minify -s website/ -d ../public/ -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.110.0"

[context.next.environment]
  HUGO_ENABLEGITINFO = "true"

# =================================================================================================
# BUILD PLUGINS
# =================================================================================================
[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

# =================================================================================================
# FUNCTIONS
# =================================================================================================
[functions]
  directory = "functions/"
