[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
TZ = "Europe/Bucharest"

[context.production.environment]
HUGO_VERSION = "0.104.1"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify"

[context.deploy-preview.environment]
HUGO_VERSION = "0.104.1"

[context.branch-deploy]
command = "hugo --gc --minify"

[context.branch-deploy.environment]
HUGO_VERSION = "0.104.1"