[build]
  command = "hugo --gc --minify"
  publish = "public"

[build.environment]
TZ = "Europe/Bucharest"

[context.production.environment]
HUGO_VERSION = "0.107.0"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --buildDrafts --buildFuture"

[context.deploy-preview.environment]
HUGO_VERSION = "0.107.0"

[context.branch-deploy]
command = "hugo --gc"

[context.branch-deploy.environment]
HUGO_VERSION = "0.107.0"