# =================================================================================================
# BUILD SETTINGS
# =================================================================================================
[build]
  publish = "public"
  command = "npm run build"
  edge_functions = "edge-functions/"

[build.environment]
  HUGO_VERSION = "0.110.0"

[build.processing]
  skip_processing = true

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# =================================================================================================
# BUILD PLUGINS
# =================================================================================================
[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"

  [plugins.inputs]
  debug = true
  srcdir = "./website"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

# =================================================================================================
# FUNCTIONS
# =================================================================================================
[functions]
  directory = "functions/"

[[edge_functions]]
function = "send-contact-email"
path = "/contact/submit"