# Content organization
---
# Keyword associated to a blog post
tag: tags

# A collection of blog posts and blog series on the same format/style
category: categories

# A collection of blog posts on the same subject, breaking down a bigger topic into multi-part blog post(s)
series: series

# A collection of articles written by the same author
author: authors
