---
name: Terraform Apply Template
description: Apply a terraform plan file from an artifact

inputs:
  terraform_directory:
    description: Directory that holds Terraform code
    required: true
  terraform_version: 
    description: Terraform Version
    required: true
  github_token: 
    description: GitHub token for auth
    required: true
  terraform_token:
    description: Terraform token for auth to TF Cloud
    required: true
  pr_id:
    description: Pull request ID
    required: true

runs:
  using: composite
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ inputs.terraforom_version }}
        terraform_wrapper: false

    - name: Terraform Init
      uses: ./.github/templates/terraform/init
      with:
        terraform_directory: "infrastructure/cloudflare"
        terraform_token: ${{ inputs.terraform_token }}

    - name: Download Plan
      id: download-plan
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{ inputs.github_token }}
        workflow: terraform-plan.yaml
        pr: ${{ inputs.pr_id }}
        name: ${{ inputs.pr_id }}-tf-plan
        path: ${{ inputs.terraform_directory }}

    - name: Terraform Apply
      id: apply
      working-directory: ${{ inputs.terraform_directory }}
      shell: bash
      run: |
        echo 'apply<<EOF' >> $GITHUB_OUTPUT
        terraform apply -input=false -no-color tfplan >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT

    - name: Comment Apply
      id: comment-apply
      uses: peter-evans/create-or-update-comment@v2
      with:
        token: ${{ inputs.github_token }}
        issue-number: ${{ inputs.pr_id }}
        body: |
          Terraform Apply:

          ```
          ${{ steps.apply.outputs.apply }}
          ```
