name: Chore
description: A boring task related to website administration.

title: ":broom: "

labels: ["🧹 Chore"]
assignees:
  - mirceanton 

body:
  - type: textarea
    id: chore-describe
    attributes:
      label: Describe the task
    validations:
      required: true
