---
name: Terraform Plan Template
description: Run the `terraform plan` command and push the output as a comment to the PR

inputs:
  terraform_directory:
    description: Directory that holds Terraform code
    required: true
  terraform_version: 
    description: Terraform Version
    required: true
  terraform_token:
    description: Terraform token for auth to TF Cloud
    required: true
  github_token: 
    description: GitHub token for auth
    required: true
  pr_id:
    description: Pull request ID
    required: true

runs:
  using: composite
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ inputs.terraforom_version }}
        terraform_wrapper: false

    - name: Terraform Init
      uses: ./.github/templates/terraform/init
      with:
        terraform_directory: "infrastructure/cloudflare"
        terraform_token: ${{ inputs.terraform_token }}

    - name: Terraform Plan
      id: plan
      working-directory: ${{ inputs.terraform_directory }}
      shell: bash
      run: |
        echo 'plan<<EOF' >> $GITHUB_OUTPUT
        terraform plan -no-color -out=tfplan >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT

    - name: Save Artifact
      id: save-artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.pr_id }}-tf-plan
        path: ${{ inputs.terraform_directory }}/tfplan

    - name: Comment Plan
      id: comment-plan
      uses: peter-evans/create-or-update-comment@v2
      with:
        token: ${{ inputs.github_token }}
        issue-number: ${{ inputs.pr_id }}
        body: |
          Terraform Plan:

          ```
          ${{ steps.plan.outputs.plan }}
          ```

          Plan saved to GH artifacts.
