---
name: Initialize Terraform
description: Configure the backend and run the `terraform init` command

inputs:
  terraform_directory:
    description: Directory that holds Terraform code
    required: true

runs:
  using: composite
  steps:
    - name: Inject Terraform Cloud Credentials
      shell: bash
      run: |
        mkdir -p ~/.terraform.d
        touch ~/.terraform.d/credentials.tfrc.json
        cat > ~/.terraform.d/credentials.tfrc.json << EOF
        {
          "credentials": {
            "app.terraform.io": {
              "token": "${{ secrets.TF_TOKEN }}"
            }
          }
        }
        EOF

    - name: Terraform Init
      id: init
      working-directory: ${{ inputs.terraform_directory }}
      shell: bash
      run: terraform init
