---
name: Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - infrastructure/**
      - .github/workflows/terraform-*

env:
  TF_IN_AUTOMATION: true
  TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN }}

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    container: hashicorp/terraform:1.4
    steps:
      - name: Terraform Init
        working-directory: ./infrastructure/
        run: terraform init

      - name: Terraform Apply
        working-directory: ./infrastructure/
        run: terraform apply
