---
name: Terraform Apply

on:
  pull_request_review:
    types: [ submitted ]

env:
  TERRAFORM_VERSION: 1.5.7
  TF_IN_AUTOMATION: true

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get PR ID
        id: pr-id
        shell: bash
        env:
          GITHUB_REF: ${{ inputs.github_ref }}
        run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_OUTPUT

      - name: Terraform Apply
        uses: ./.github/templates/terraform/apply
        with:
          terraform_directory: "infrastructure/cloudflare"
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_id: ${{ steps.pr-id.outputs.PR_NUMBER }}
