---
name: Terraform Apply

on:
  push:
    branches:
      - main
    paths:
      - infrastructure/**
      - .github/workflows/terraform-*

env:
  TF_IN_AUTOMATION: true
  TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN }}
  TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  TF_VAR_cloudflare_account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

jobs:
  terraform-cd:
    runs-on: ubuntu-latest
    # container: antonmircea/terraform # FIXME
    defaults:
     run:
       shell: bash
       working-directory: infrastructure/

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
